"""empty message

Revision ID: 06163ab5c64f
Revises: 24c697abd12d
Create Date: 2018-12-09 14:58:57.332957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06163ab5c64f'
down_revision = '24c697abd12d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
