"""empty message

Revision ID: 0beb28c486bb
Revises: 02722985f764
Create Date: 2018-11-18 11:56:42.042424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0beb28c486bb'
down_revision = '02722985f764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
